name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  runs-on: ubuntu-latest
  steps:
  github-metrics:
    - name: Classic     
          uses: lowlighter/metrics@latest
          with:
            token: ${{ secrets.METRICS_TOKEN }}
    - name: Snippet
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.code.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_code: yes
