name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Classic     
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
      - name: Snippet
        uses: lowlighter/metrics@latest
        with:
          filename: snippet.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_code: yes
          plugin_code_lines: 12               # Only display snippets with less than 12 lines
          plugin_code_load: 100               # Fetch 100 events from activity
          plugin_code_visibility: public      # Only display snippets from public activity
      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          filename: habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits: yes
          plugin_habits_from: 200          # Use 200 events to compute habits
          plugin_habits_days: 14           # Keep only events from last 14 days
          plugin_habits_facts: yes         # Display facts section
          plugin_habits_charts: yes        # Display charts section
          plugin_habits_trim: yes          # Trim unused hours on daily chart
          config_timezone: Europe/Istanbul # Set timezone
